version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - echo "Setting environment variables to disable ESLint..."
            - export DISABLE_ESLINT_PLUGIN=true
            - export NEXT_DISABLE_ESLINT=1
            - echo "Building the application..."
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .next/cache/**/*
    appRoot: pfas-claim-website 